### ISSUE TITLE
R script error 404 task 206 failed

### ISSUE THREAD

**Issue by Gringooooo** [JesseVent/crypto#11]
Hi,
First, many thanks for this great development.
Until a few days ago I was scraping coinmarketcap historical data for all coins thanks to Excel and Power Query. It was working fine, but it was taking a long time.
When I have discovered your project a few days ago I have decided to give it a go. It took me some time to get everything set up as it was the first time for me to use R.
Finally, after a few hours everything was working fine.
I managed to used it for a few days, but now I have an error.

When I try to load the historical data with the standard command “will_i_get_rich <- getCoins()” the process goes to 100% but then I have an error message:

100%Error in scraper(attributes[i], slug[i]) : 
  task 206 failed - "HTTP error 404."

I tried another time and in addition I get this message:

In addition: Warning messages:
1: closing unused connection 10 (<-www.bitsumactivationserver.com:11972) 
2: closing unused connection 9 (<-www.bitsumactivationserver.com:11972) 
3: closing unused connection 8 (<-www.bitsumactivationserver.com:11972) 
4: closing unused connection 7 (<-www.bitsumactivationserver.com:11972) 
5: closing unused connection 6 (<-www.bitsumactivationserver.com:11972) 
6: closing unused connection 5 (<-www.bitsumactivationserver.com:11972) 
7: closing unused connection 4 (<-www.bitsumactivationserver.com:11972) 
8: closing unused connection 3 (<-www.bitsumactivationserver.com:11972)

From what I understand, coinmarketcap is (now) using a kind of firewall to avoid DDoD attack or server overload. Do you think it could be the reason for the HTTP error and do you think there is way to avoid this error.

Many thanks again for your tool ;-)
Regards,
G

**Comment by Gringooooo** [comment]
One additional information, I just tried to retrieve the data by using a VPN and I have the same issue, which mean it is not due to my IP address which could blacklisted due to too many request on their server.

**Comment by JesseVent** [comment]
Thanks for letting me know, I debugged the scraper function and looks like CoinMarketCap include Coindash in there list coins API call, which is how it gets inherited as #206 on that list. When the scraper opens that page to start extracting data it gets a 404 error because the page doesn't actually exist on CMC. 

![coindash](https://user-images.githubusercontent.com/16379819/37153994-7cf16a00-232e-11e8-8cf6-4d92366223f6.png)

I'd noticed a couple of times id gotten similar errors around the 1300-1400 mark but never looked too much into it.

I've now implemented error handling built into the scraper so if it receives an error from one of the pages it'll just skip it. Change is committed to Github, but ill wait a week or so before resubmitting to CRAN.

In the mean time it can be installed by the following:
```
install.packages("devtools")
devtools::install_github("jessevent/crypto")
```

**Comment by Gringooooo** [comment]
Many thanks for the feedback and the update.
I just launched it and it worked like a charm.

I just want to report that now at the end of the update I have this message:

100%
   user  system elapsed 
  16.42    0.80  378.64 
Warning messages:
1: In function_list[[k]](value) : NAs introduced by coercion
2: In function_list[[k]](value) : NAs introduced by coercion

I don’t know if it is important or not.
Thanks again.
G
