### ISSUE TITLE
Error in UseMethod("replace_na")

### ISSUE THREAD

**Issue by HakanHolmberg** [JesseVent/crypto#14]
Hi and thanks for a great package.

When I try to execute the following code:
cryptoData <- getCoins()

I get the following result:  |=============================================================================================================================================================================| 100%
   user  system elapsed 
 34.748   0.748 615.073 
 Error in UseMethod("replace_na"): 
 no applicable method for 'replace_na' applied to an object of class "character"
> 

my session Info is:
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=sv_SE.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=sv_SE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=sv_SE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=sv_SE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] doSNOW_1.0.16   snow_0.4-2      iterators_1.0.8 curl_2.6        lubridate_1.7.3 dplyr_0.5.0     jsonlite_1.4    magrittr_1.5    tidyr_0.6.1     Rcpp_0.12.16    crypto_0.1.5   
[12] rvest_0.3.2     xml2_1.1.1      foreach_1.4.3  

loaded via a namespace (and not attached):
 [1] codetools_0.2-15 assertthat_0.2.0 R6_2.2.0         DBI_0.6-1        httr_1.2.1       stringi_1.1.5    lazyeval_0.2.0   tools_3.4.3      stringr_1.2.0    compiler_3.4.3  
[11] tibble_1.3.0 

I would love some help with this error message since I really want to use your package.

best regards,
Haakan

**Comment by HakanHolmberg** [comment]
I fixed the problem by installing the github version of the package.

**Comment by mushrooman** [comment]
Downloading GitHub repo jessevent/crypto@master
from URL https://api.github.com/repos/jessevent/crypto/zipball/master
Installing crypto
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/mushrooman/AppData/Local/Temp/RtmpsfIfUr/devtools3d68ce17343/JesseVent-crypto-ffa2702"  \
  --library="C:/Users/mushrooman/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'crypto' ...
** R
** inst
** preparing package for lazy loading
Warning: package 'foreach' was built under R version 3.4.2
Warning: package 'rvest' was built under R version 3.4.2
Warning: package 'xml2' was built under R version 3.4.2
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Warning: package 'foreach' was built under R version 3.4.2
Warning: package 'rvest' was built under R version 3.4.2
Warning: package 'xml2' was built under R version 3.4.2
*** arch - x64
Warning: package 'foreach' was built under R version 3.4.2
Warning: package 'rvest' was built under R version 3.4.2
Warning: package 'xml2' was built under R version 3.4.2
* DONE (crypto)

Warning: DEPRECATED: Please use crypto_history() instead of getCoins().
Retrieves coin market history from CoinMarketCap. Warning in replace_encoding(sys_locale) :
  Temporarily changing locale encoding from Chinese (Simplified)_China.936 to UTF-8. Will reset back to Chinese (Simplified)_China.936

  |                                                                                                                                                    
  |                                                                                                                                              |   0%   If this helps you become rich please consider donating
ERC-20: 0x375923Bf82F0b728d23A5704261a6e16341fd860
XRP: rK59semLsuJZEWftxBFhWuNE6uhznjz2bK
LTC: LWpiZMd2cEyqCdrZrs9TjsouTLWbFFxwCj

  |                                                                                                                                                    
  |=                                                                                                                                             |   0%
  |                                                                                                                                                    
  |=                                                                                                                                             |   1%
  |                                                                                                                                                    
  |==                                                                                                                                            |   1%
  |                                                                                                                                                    
  |==                                                                                                                                            |   2%
  |                                                                                                                                                    
  |===                                                                                                                                           |   2%
  |                                                                                                                                                    
  |====                                                                                                                                          |   2%
  |                                                                                                                                                    
  |====                                                                                                                                          |   3%
  |                                                                                                                                                    
  |=====                                                                                                                                         |   3%
  |                                                                                                                                                    
  |=====                                                                                                                                         |   4%
  |                                                                                                                                                    
  |======                                                                                                                                        |   4%
  |                                                                                                                                                    
  |======                                                                                                                                        |   5%
  |                                                                                                                                                    
  |=======                                                                                                                                       |   5%
  |                                                                                                                                                    
  |========                                                                                                                                      |   5%
  |                                                                                                                                                    
  |========                                                                                                                                      |   6%
  |                                                                                                                                                    
  |=========                                                                                                                                     |   6%
  |                                                                                                                                                    
  |=========                                                                                                                                     |   7%
  |                                                                                                                                                    
  |==========                                                                                                                                    |   7%
  |                                                                                                                                                    
  |===========                                                                                                                                   |   7%
  |                                                                                                                                                    
  |===========                                                                                                                                   |   8%
  |                                                                                                                                                    
  |============                                                                                                                                  |   8%
  |                                                                                                                                                    
  |============                                                                                                                                  |   9%
  |                                                                                                                                                    
  |=============                                                                                                                                 |   9%
  |                                                                                                                                                    
  |==============                                                                                                                                |  10%
  |                                                                                                                                                    
  |===============                                                                                                                               |  10%
  |                                                                                                                                                    
  |===============                                                                                                                               |  11%
  |                                                                                                                                                    
  |================                                                                                                                              |  11%
  |                                                                                                                                                    
  |================                                                                                                                              |  12%
  |                                                                                                                                                    
  |=================                                                                                                                             |  12%
  |                                                                                                                                                    
  |==================                                                                                                                            |  12%
  |                                                                                                                                                    
  |==================                                                                                                                            |  13%
  |                                                                                                                                                    
  |===================                                                                                                                           |  13%
  |                                                                                                                                                    
  |===================                                                                                                                           |  14%
  |                                                                                                                                                    
  |====================                                                                                                                          |  14%
  |                                                                                                                                                    
  |=====================                                                                                                                         |  14%
  |                                                                                                                                                    
  |=====================                                                                                                                         |  15%
  |                                                                                                                                                    
  |======================                                                                                                                        |  15%
  |                                                                                                                                                    
  |======================                                                                                                                        |  16%
  |                                                                                                                                                    
  |=======================                                                                                                                       |  16%
  |                                                                                                                                                    
  |=======================                                                                                                                       |  17%
  |                                                                                                                                                    
  |========================                                                                                                                      |  17%
  |                                                                                                                                                    
  |=========================                                                                                                                     |  17%
  |                                                                                                                                                    
  |=========================                                                                                                                     |  18%
  |                                                                                                                                                    
  |==========================                                                                                                                    |  18%
  |                                                                                                                                                    
  |==========================                                                                                                                    |  19%
  |                                                                                                                                                    
  |===========================                                                                                                                   |  19%
  |                                                                                                                                                    
  |============================                                                                                                                  |  19%
  |                                                                                                                                                    
  |============================                                                                                                                  |  20%
  |                                                                                                                                                    
  |=============================                                                                                                                 |  20%
  |                                                                                                                                                    
  |=============================                                                                                                                 |  21%
  |                                                                                                                                                    
  |==============================                                                                                                                |  21%
  |                                                                                                                                                    
  |===============================                                                                                                               |  22%
  |                                                                                                                                                    
  |================================                                                                                                              |  22%
  |                                                                                                                                                    
  |================================                                                                                                              |  23%
  |                                                                                                                                                    
  |=================================                                                                                                             |  23%
  |                                                                                                                                                    
  |=================================                                                                                                             |  24%
  |                                                                                                                                                    
  |==================================                                                                                                            |  24%
  |                                                                                                                                                    
  |===================================                                                                                                           |  24%
  |                                                                                                                                                    
  |===================================                                                                                                           |  25%
  |                                                                                                                                                    
  |====================================                                                                                                          |  25%
  |                                                                                                                                                    
  |====================================                                                                                                          |  26%
  |                                                                                                                                                    
  |=====================================                                                                                                         |  26%
  |                                                                                                                                                    
  |======================================                                                                                                        |  26%
  |                                                                                                                                                    
  |======================================                                                                                                        |  27%
  |                                                                                                                                                    
  |=======================================                                                                                                       |  27%
  |                                                                                                                                                    
  |=======================================                                                                                                       |  28%
  |                                                                                                                                                    
  |========================================                                                                                                      |  28%
  |                                                                                                                                                    
  |=========================================                                                                                                     |  29%
  |                                                                                                                                                    
  |==========================================                                                                                                    |  29%
  |                                                                                                                                                    
  |==========================================                                                                                                    |  30%
  |                                                                                                                                                    
  |===========================================                                                                                                   |  30%
  |                                                                                                                                                    
  |===========================================                                                                                                   |  31%
  |                                                                                                                                                    
  |============================================                                                                                                  |  31%
  |                                                                                                                                                    
  |=============================================                                                                                                 |  31%
  |                                                                                                                                                    
  |=============================================                                                                                                 |  32%
  |                                                                                                                                                    
  |==============================================                                                                                                |  32%
  |                                                                                                                                                    
  |==============================================                                                                                                |  33%
  |                                                                                                                                                    
  |===============================================                                                                                               |  33%
  |                                                                                                                                                    
  |================================================                                                                                              |  33%
  |                                                                                                                                                    
  |================================================                                                                                              |  34%
  |                                                                                                                                                    
  |=================================================                                                                                             |  34%
  |                                                                                                                                                    
  |=================================================                                                                                             |  35%
  |                                                                                                                                                    
  |==================================================                                                                                            |  35%
  |                                                                                                                                                    
  |==================================================                                                                                            |  36%
  |                                                                                                                                                    
  |===================================================                                                                                           |  36%
  |                                                                                                                                                    
  |====================================================                                                                                          |  36%
  |                                                                                                                                                    
  |====================================================                                                                                          |  37%
  |                                                                                                                                                    
  |=====================================================                                                                                         |  37%
  |                                                                                                                                                    
  |=====================================================                                                                                         |  38%
  |                                                                                                                                                    
  |======================================================                                                                                        |  38%
  |                                                                                                                                                    
  |=======================================================                                                                                       |  38%
  |                                                                                                                                                    
  |=======================================================                                                                                       |  39%
  |                                                                                                                                                    
  |========================================================                                                                                      |  39%
  |                                                                                                                                                    
  |========================================================                                                                                      |  40%
  |                                                                                                                                                    
  |=========================================================                                                                                     |  40%
  |                                                                                                                                                    
  |==========================================================                                                                                    |  41%
  |                                                                                                                                                    
  |===========================================================                                                                                   |  41%
  |                                                                                                                                                    
  |===========================================================                                                                                   |  42%
  |                                                                                                                                                    
  |============================================================                                                                                  |  42%
  |                                                                                                                                                    
  |============================================================                                                                                  |  43%
  |                                                                                                                                                    
  |=============================================================                                                                                 |  43%
  |                                                                                                                                                    
  |==============================================================                                                                                |  43%
  |                                                                                                                                                    
  |==============================================================                                                                                |  44%
  |                                                                                                                                                    
  |===============================================================                                                                               |  44%
  |                                                                                                                                                    
  |===============================================================                                                                               |  45%
  |                                                                                                                                                    
  |================================================================                                                                              |  45%
  |                                                                                                                                                    
  |=================================================================                                                                             |  45%
  |                                                                                                                                                    
  |=================================================================                                                                             |  46%
  |                                                                                                                                                    
  |==================================================================                                                                            |  46%
  |                                                                                                                                                    
  |==================================================================                                                                            |  47%
  |                                                                                                                                                    
  |===================================================================                                                                           |  47%
  |                                                                                                                                                    
  |====================================================================                                                                          |  48%
  |                                                                                                                                                    
  |=====================================================================                                                                         |  48%
  |                                                                                                                                                    
  |=====================================================================                                                                         |  49%
  |                                                                                                                                                    
  |======================================================================                                                                        |  49%
  |                                                                                                                                                    
  |======================================================================                                                                        |  50%
  |                                                                                                                                                    
  |=======================================================================                                                                       |  50%
  |                                                                                                                                                    
  |========================================================================                                                                      |  50%
  |                                                                                                                                                    
  |========================================================================                                                                      |  51%
  |                                                                                                                                                    
  |=========================================================================                                                                     |  51%
  |                                                                                                                                                    
  |=========================================================================                                                                     |  52%
  |                                                                                                                                                    
  |==========================================================================                                                                    |  52%
  |                                                                                                                                                    
  |===========================================================================                                                                   |  53%
  |                                                                                                                                                    
  |============================================================================                                                                  |  53%
  |                                                                                                                                                    
  |============================================================================                                                                  |  54%
  |                                                                                                                                                    
  |=============================================================================                                                                 |  54%
  |                                                                                                                                                    
  |=============================================================================                                                                 |  55%
  |                                                                                                                                                    
  |==============================================================================                                                                |  55%
  |                                                                                                                                                    
  |===============================================================================                                                               |  55%
  |                                                                                                                                                    
  |===============================================================================                                                               |  56%
  |                                                                                                                                                    
  |================================================================================                                                              |  56%
  |                                                                                                                                                    
  |================================================================================                                                              |  57%
  |                                                                                                                                                    
  |=================================================================================                                                             |  57%
  |                                                                                                                                                    
  |==================================================================================                                                            |  57%
  |                                                                                                                                                    
  |==================================================================================                                                            |  58%
  |                                                                                                                                                    
  |===================================================================================                                                           |  58%
  |                                                                                                                                                    
  |===================================================================================                                                           |  59%
  |                                                                                                                                                    
  |====================================================================================                                                          |  59%
  |                                                                                                                                                    
  |=====================================================================================                                                         |  60%
  |                                                                                                                                                    
  |======================================================================================                                                        |  60%
  |                                                                                                                                                    
  |======================================================================================                                                        |  61%
  |                                                                                                                                                    
  |=======================================================================================                                                       |  61%
  |                                                                                                                                                    
  |=======================================================================================                                                       |  62%
  |                                                                                                                                                    
  |========================================================================================                                                      |  62%
  |                                                                                                                                                    
  |=========================================================================================                                                     |  62%
  |                                                                                                                                                    
  |=========================================================================================                                                     |  63%
  |                                                                                                                                                    
  |==========================================================================================                                                    |  63%
  |                                                                                                                                                    
  |==========================================================================================                                                    |  64%
  |                                                                                                                                                    
  |===========================================================================================                                                   |  64%
  |                                                                                                                                                    
  |============================================================================================                                                  |  64%
  |                                                                                                                                                    
  |============================================================================================                                                  |  65%
  |                                                                                                                                                    
  |=============================================================================================                                                 |  65%
  |                                                                                                                                                    
  |=============================================================================================                                                 |  66%
  |                                                                                                                                                    
  |==============================================================================================                                                |  66%
  |                                                                                                                                                    
  |==============================================================================================                                                |  67%
  |                                                                                                                                                    
  |===============================================================================================                                               |  67%
  |                                                                                                                                                    
  |================================================================================================                                              |  67%
  |                                                                                                                                                    
  |================================================================================================                                              |  68%
  |                                                                                                                                                    
  |=================================================================================================                                             |  68%
  |                                                                                                                                                    
  |=================================================================================================                                             |  69%
  |                                                                                                                                                    
  |==================================================================================================                                            |  69%
  |                                                                                                                                                    
  |===================================================================================================                                           |  69%
  |                                                                                                                                                    
  |===================================================================================================                                           |  70%
  |                                                                                                                                                    
  |====================================================================================================                                          |  70%
  |                                                                                                                                                    
  |====================================================================================================                                          |  71%
  |                                                                                                                                                    
  |=====================================================================================================                                         |  71%
  |                                                                                                                                                    
  |======================================================================================================                                        |  72%
  |                                                                                                                                                    
  |=======================================================================================================                                       |  72%
  |                                                                                                                                                    
  |=======================================================================================================                                       |  73%
  |                                                                                                                                                    
  |========================================================================================================                                      |  73%
  |                                                                                                                                                    
  |========================================================================================================                                      |  74%
  |                                                                                                                                                    
  |=========================================================================================================                                     |  74%
  |                                                                                                                                                    
  |==========================================================================================================                                    |  74%
  |                                                                                                                                                    
  |==========================================================================================================                                    |  75%
  |                                                                                                                                                    
  |===========================================================================================================                                   |  75%
  |                                                                                                                                                    
  |===========================================================================================================                                   |  76%
  |                                                                                                                                                    
  |============================================================================================================                                  |  76%
  |                                                                                                                                                    
  |=============================================================================================================                                 |  76%
  |                                                                                                                                                    
  |=============================================================================================================                                 |  77%
  |                                                                                                                                                    
  |==============================================================================================================                                |  77%
  |                                                                                                                                                    
  |==============================================================================================================                                |  78%
  |                                                                                                                                                    
  |===============================================================================================================                               |  78%
  |                                                                                                                                                    
  |================================================================================================================                              |  79%
  |                                                                                                                                                    
  |=================================================================================================================                             |  79%
  |                                                                                                                                                    
  |=================================================================================================================                             |  80%
  |                                                                                                                                                    
  |==================================================================================================================                            |  80%
  |                                                                                                                                                    
  |==================================================================================================================                            |  81%
  |                                                                                                                                                    
  |===================================================================================================================                           |  81%
  |                                                                                                                                                    
  |====================================================================================================================                          |  81%
  |                                                                                                                                                    
  |====================================================================================================================                          |  82%
  |                                                                                                                                                    
  |=====================================================================================================================                         |  82%
  |                                                                                                                                                    
  |=====================================================================================================================                         |  83%
  |                                                                                                                                                    
  |======================================================================================================================                        |  83%
  |                                                                                                                                                    
  |=======================================================================================================================                       |  83%
  |                                                                                                                                                    
  |=======================================================================================================================                       |  84%
  |                                                                                                                                                    
  |========================================================================================================================                      |  84%
  |                                                                                                                                                    
  |========================================================================================================================                      |  85%
  |                                                                                                                                                    
  |=========================================================================================================================                     |  85%
  |                                                                                                                                                    
  |=========================================================================================================================                     |  86%
  |                                                                                                                                                    
  |==========================================================================================================================                    |  86%
  |                                                                                                                                                    
  |===========================================================================================================================                   |  86%
  |                                                                                                                                                    
  |===========================================================================================================================                   |  87%
  |                                                                                                                                                    
  |============================================================================================================================                  |  87%
  |                                                                                                                                                    
  |============================================================================================================================                  |  88%
  |                                                                                                                                                    
  |=============================================================================================================================                 |  88%
  |                                                                                                                                                    
  |==============================================================================================================================                |  88%
  |                                                                                                                                                    
  |==============================================================================================================================                |  89%
  |                                                                                                                                                    
  |===============================================================================================================================               |  89%
  |                                                                                                                                                    
  |===============================================================================================================================               |  90%
  |                                                                                                                                                    
  |================================================================================================================================              |  90%
  |                                                                                                                                                    
  |=================================================================================================================================             |  91%
  |                                                                                                                                                    
  |==================================================================================================================================            |  91%
  |                                                                                                                                                    
  |==================================================================================================================================            |  92%
  |                                                                                                                                                    
  |===================================================================================================================================           |  92%
  |                                                                                                                                                    
  |===================================================================================================================================           |  93%
  |                                                                                                                                                    
  |====================================================================================================================================          |  93%
  |                                                                                                                                                    
  |=====================================================================================================================================         |  93%
  |                                                                                                                                                    
  |=====================================================================================================================================         |  94%
  |                                                                                                                                                    
  |======================================================================================================================================        |  94%
  |                                                                                                                                                    
  |======================================================================================================================================        |  95%
  |                                                                                                                                                    
  |=======================================================================================================================================       |  95%
  |                                                                                                                                                    
  |========================================================================================================================================      |  95%
  |                                                                                                                                                    
  |========================================================================================================================================      |  96%
  |                                                                                                                                                    
  |=========================================================================================================================================     |  96%
  |                                                                                                                                                    
  |=========================================================================================================================================     |  97%
  |                                                                                                                                                    
  |==========================================================================================================================================    |  97%
  |                                                                                                                                                    
  |==========================================================================================================================================    |  98%
  |                                                                                                                                                    
  |===========================================================================================================================================   |  98%
  |                                                                                                                                                    
  |============================================================================================================================================  |  98%
  |                                                                                                                                                    
  |============================================================================================================================================  |  99%
  |                                                                                                                                                    
  |============================================================================================================================================= |  99%
  |                                                                                                                                                    
  |============================================================================================================================================= | 100%
  |                                                                                                                                                    
  |==============================================================================================================================================| 100%
   user  system elapsed 
   3.25    2.80  703.14 
Error in UseMethod("replace_na") : 
  no applicable method for 'replace_na' applied to an object of class "character"


i install the package from github, but still have the "Error in UseMethod("replace_na") " problem
any suggestion is greatly appreciated.
