### ISSUE TITLE
Error in today() : could not find function "today"

### ISSUE THREAD

**Issue by koloks** [JesseVent/crypto#4]
Today function is missing from the crypto function
## Detailed Description

after loading the crypto library I run the following and receive 

will_i_get_rich <- getCoins()
Error in today() : could not find function "today"

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by JesseVent** [comment]
Can you please try calling `install.packages("lubridate")` and try again. Today is part of the lubridate package which should of installed as a dependency

**Comment by koloks** [comment]
thank you have tried that and I rceived
Error in data_frame(symbol = coins$symbol, name = coins$name, slug = coins$slug,  : 
  could not find function "data_frame"

**Comment by koloks** [comment]
Thank you that has worked. Great stuff.

**Comment by koloks** [comment]
Hey Jesse thanks for the great package. Saved me ally of time. Great work. Out of interest in the time series of prices the filed close_ratio how is it calculated?

I can figure that one out

Spiro

**Comment by JesseVent** [comment]
No problems, it’s weird it didn’t automatically install when you installed the package though.

Close_ratio is using a min/max function (close_price - low_price) / (high_price - low_price) which standardises the close_price to a value of 0 to 1 depending on how physically close the amount is from either the low or high price. I.e. if it’s 0.40 then it’s indicating the market closed trending lower instead of higher
