### ISSUE TITLE
Symbols coming in Repeated

### ISSUE THREAD

**Issue by GrayAlex49** [JesseVent/crypto#8]
I've tried `getCoins()` twice tonight and the symbol column seems messed up.  For example Bitcoins symbol both times I pulled it is 'BTCBITCOINBTC', Ethereum is 'ETHETHEREUMETH'.  It looks like something I could filter out but I assume this is not the desired behavior.  Just a heads up.  Using R 3.4.3, crypto at current CRAN version.

**Comment by Mdubois12** [comment]
I am also seeing the same thing on the same version of R and CRAN.

Looks like it started yesterday (2-8-2018)

![image](https://user-images.githubusercontent.com/6621547/36030332-c1e1226a-0d74-11e8-80ba-20f5594418af.png)

**Comment by JesseVent** [comment]
Hmm coinmarketcap must of updated their page i'm scraping from, I've rewritten  the package to merge the name and symbol in based on the slug, rather than attempt retrieve it from the table. 

```
library(devtools)
install_github("jessevent/crypto")
```
Can you run the above and let me know if that fixes it for you?  

Thanks

**Comment by GrayAlex49** [comment]
Yeah that works.  Thanks for fixing that.

**Comment by Mdubois12** [comment]
Works for me too. Thanks!

**Comment by JesseVent** [comment]
Awesome, thanks guys for letting me know, I’ll submit the update on CRAN.  Due to how I implemented the fix, it allowed me to make the scraping function generic and add an additional function to scrape the exchanges each token is on. 
`exchanges <- getExchanges()` will provide you with all the listed exchanges.
